In [1]:
import pandas as pd

In [46]:
hotels = pd.read_csv('hotels.csv')
hotels.head(3)

,hotel_address,additional_number_of_scoring,review_date,average_score,hotel_name,reviewer_nationality,negative_review,review_total_negative_word_counts,total_number_of_reviews,positive_review,review_total_positive_word_counts,total_number_of_reviews_reviewer_has_given,reviewer_score,tags,days_since_review,lat,lng
0,Stratton Street Mayfair Westminster Borough Lo...,581,2/19/2016,8.4,The May Fair Hotel,United Kingdom,Leaving,3,1994,Staff were amazing,4,7,10.0,"[' Leisure trip ', ' Couple ', ' Studio Suite ...",531 day,51.507894,-0.143671
1,130 134 Southampton Row Camden London WC1B 5AF...,299,1/12/2017,8.3,Mercure London Bloomsbury Hotel,United Kingdom,poor breakfast,3,1361,location,2,14,6.3,"[' Business trip ', ' Couple ', ' Standard Dou...",203 day,51.521009,-0.123097
2,151 bis Rue de Rennes 6th arr 75006 Paris France,32,10/18/2016,8.9,Legend Saint Germain by Elegancia,China,No kettle in room,6,406,No Positive,0,14,7.5,"[' Leisure trip ', ' Solo traveler ', ' Modern...",289 day,48.845377,2.325643

In [47]:
hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386803 entries, 0 to 386802
Data columns (total 17 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   hotel_address                               386803 non-null  object
 1   additional_number_of_scoring                386803 non-null  int64
 2   review_date                                 386803 non-null  object
 3   average_score                               386803 non-null  float64
 4   hotel_name                                  386803 non-null  object
 5   reviewer_nationality                        386803 non-null  object
 6   negative_review                             386803 non-null  object
 7   review_total_negative_word_counts           386803 non-null  int64
 8   total_number_of_reviews                     386803 non-null  int64
 9   positive_review                             386803 non-null  object
 10  review_total_positive_word_counts           386803 non-null  int64
 11  total_number_of_reviews_reviewer_has_given  386803 non-null  int64
 12  reviewer_score                              386803 non-null  float64
 13  tags                                        386803 non-null  object
 14  days_since_review                           386803 non-null  object
 15  lat                                         384355 non-null  float64
 16  lng                                         384355 non-null  float64
dtypes: float64(4), int64(5), object(8)
memory usage: 50.2+ MB

In [48]:
hotels.nunique()

hotel_address                                   1493
additional_number_of_scoring                     480
review_date                                      731
average_score                                     34
hotel_name                                      1492
reviewer_nationality                             225
negative_review                               248828
review_total_negative_word_counts                402
total_number_of_reviews                         1142
positive_review                               311737
review_total_positive_word_counts                354
total_number_of_reviews_reviewer_has_given       194
reviewer_score                                    37
tags                                           47135
days_since_review                                731
lat                                             1472
lng                                             1472
dtype: int64

In [49]:
hotels['review_date'] = pd.to_datetime(hotels['review_date'])

In [50]:
hotels['review_date'].min()
hotels['review_date'].max()

Timestamp('2017-08-03 00:00:00')

In [54]:
hotels['tags']

0         [' Leisure trip ', ' Couple ', ' Studio Suite ...
1         [' Business trip ', ' Couple ', ' Standard Dou...
2         [' Leisure trip ', ' Solo traveler ', ' Modern...
3         [' Leisure trip ', ' Solo traveler ', ' Standa...
4         [' Business trip ', ' Couple ', ' Standard Dou...
                                ...
386798    [' Leisure trip ', ' Group ', ' Club Double or...
386799    [' Leisure trip ', ' Couple ', ' Standard Doub...
386800    [' Business trip ', ' Solo traveler ', ' Singl...
386801    [' Leisure trip ', ' Solo traveler ', ' Deluxe...
386802    [' Leisure trip ', ' Couple ', ' Bunk Bed Room...
Name: tags, Length: 386803, dtype: object

In [60]:
def collect_tags(df):
    """This function collects the tags information by type and counts
    Args:
        df (pandas.DataFrame): input data
    Returns:
        tags_list (list of the lists): [['Leisure trip', 'Couple', 'Superior Double Room', 'Stayed 1 night'], ... ['Leisure trip', 'Group', 'Large Room', 'Stayed 4 nights']]
        tags_dict (dictionary): the dictionary of tags and their counts like {'Leisure trip': 23452, 'Couple': 67 ... 'Stayed 2 nights': 345}
        
    """
    # Create empty tags list
    tags_dict = dict()
    tags_list = list()
    # Go along the rows by indexes
    for idx, row in hotels['tags'].items():
        # Get the tags from the rows
        tags = list(row.replace("[' ", '').replace(" ']", '').split(" ', ' "))
        # Fill the tags list
        tags_list.append(tags)
        for tag in tags:
            if tag not in tags_dict.keys():
                tags_dict.update({tag: 1})
            else:
                tags_dict[tag] += 1
                
    return tags_list, tags_dict


tg_list, tg_dict = collect_tags(hotels)
print(len(tg_dict))
print(tg_list[13:20])

2368
[['Leisure trip', 'Couple', 'Double or Twin Room Non Smoking', 'Stayed 1 night', 'Submitted from a mobile device'], ['Leisure trip', 'Couple', 'Double or Twin Room', 'Stayed 4 nights', 'Submitted from a mobile device'], ['Leisure trip', 'Couple', 'Double or Twin Room', 'Stayed 1 night'], ['Business trip', 'Solo traveler', 'Standard Room', 'Stayed 1 night', 'Submitted from a mobile device'], ['Leisure trip', 'Group', 'Standard Room', 'Stayed 2 nights', 'Submitted from a mobile device'], ['Leisure trip', 'Solo traveler', 'Standard Double Room', 'Stayed 2 nights'], ['Leisure trip', 'Couple', 'Comfort Double or Twin Room', 'Stayed 4 nights']]

In [66]:
tg_dict

{'Leisure trip': 313593,
 'Couple': 189212,
 'Studio Suite': 543,
 'Stayed 2 nights': 100263,
 'Submitted from a mobile device': 230778,
 'Business trip': 61989,
 'Standard Double Room': 24151,
 'Stayed 1 night': 145373,
 'Solo traveler': 81235,
 'Modern Double Room Echo': 4,
 'Stayed 3 nights': 72000,
 'Standard Room with 1 Double Bed': 677,
 'Standard Double or Twin Room': 13062,
 'Stayed 6 nights': 7399,
 'Superior Twin Room': 4540,
 'Double Room Non Smoking': 977,
 'Superior Double Room': 23550,
 'Stayed 4 nights': 35748,
 'Double Room': 26386,
 'Twin Hilton Guest Room': 711,
 'Family with young children': 45836,
 'Luxury Room': 233,
 'Double or Twin Room Non Smoking': 394,
 'Double or Twin Room': 16824,
 'Standard Room': 3171,
 'Group': 49088,
 'Comfort Double or Twin Room': 1832,
 'Standard': 934,
 'Executive Double Room': 4763,
 'Twin Room Non Smoking': 509,
 'Studio Double Family': 395,
 'Double Twin Superior Room': 21,
 'X Ordinary Room': 66,
 '2 rooms': 9287,
 'King Deluxe Guest Room': 103,
 'Double Studio': 204,
 'Family with older children': 19802,
 'Luxury Double Room': 824,
 'Standard Double Room without Window': 1808,
 'Hypoallergenic Double or Twin Room': 39,
 'Premier Double Room': 765,
 'Standard Room with Double Bed and Sofa Bed': 107,
 'Basic Double Room': 2125,
 'Classic Double Room': 12716,
 'Deluxe King Room': 3993,
 'Superior Family Room': 115,
 'Stayed 5 nights': 15611,
 'Double Guest Room': 2629,
 'Standard Twin Room': 7325,
 'Deluxe One Bedroom Apartment': 258,
 'Travelers with friends': 1630,
 'Twin Room': 6279,
 'Deluxe Double Room with Eiffel Tower view': 77,
 'Standard King Room': 450,
 'Studio': 728,
 'Standard Double or Twin Room with Extra bed 2 Adults 1 Child': 68,
 'Small Queen Room': 1890,
 'Art King Room': 467,
 'Triple Room': 3385,
 'Superior Room': 3292,
 'Superior Twin Room with Internal View': 518,
 'Deluxe Twin Room': 2309,
 'Executive Queen Room with Lounge Access': 139,
 'Deluxe Double Room': 18623,
 'Large Twin Room': 231,
 'Executive King Room': 1962,
 'Classic Double or Twin Room': 4576,
 'Single Room': 7227,
 'Superior Room with Spa access': 137,
 'Luxury Suite Patio': 32,
 'Premium Double or Twin Room with View': 25,
 'Queen Guest Room': 2355,
 'Chelsea Twin Suite': 57,
 'Executive Suite': 149,
 'Standard Room with 1 Single Bed': 268,
 'Double Hilton Deluxe Room': 188,
 'Superior Double or Twin Room with Parking': 14,
 'Standard Queen Room': 2611,
 'King Guest Room': 1202,
 'Queen Hilton Guest Room': 221,
 'Standard Double Room with Park View': 99,
 'Classic Room': 3322,
 'Executive Studio City View Family': 105,
 'Deluxe Family Room': 115,
 'Queen Room': 4071,
 'City Twin Room': 379,
 'Double Family Guestroom': 71,
 'Stayed 8 nights': 1910,
 'Deluxe Double with Terrace': 7,
 'Queen Guestroom': 85,
 'Club Double Room': 4485,
 'Large Double Room': 867,
 'River View Deluxe': 104,
 'Superior Double Room Single use': 14,
 'Deluxe Single Room': 2469,
 'Standard Double Room with View Terrace': 113,
 'Standard Single Room': 3470,
 'Apartment for 3 to 4 People with Kitchenette': 27,
 'Standard Triple Room': 1022,
 'Deluxe Double or Twin Room': 4465,
 'Double Room with Courtyard View': 442,
 'Classic Single Room': 803,
 'Superior Room with 1 Queen Bed': 131,
 'Deluxe King or Twin Room': 1234,
 'Stayed 7 nights': 5549,
 'Superior King Room': 3208,
 'Studio King': 161,
 'Club Twin Room': 1039,
 'Cosy Double Room': 1191,
 'Double Room with Spa Bath': 288,
 'Double Room with River View': 104,
 'Deluxe Double Room with Two Double Beds': 252,
 'Stayed 10 nights': 663,
 'Stayed 14 nights': 184,
 'King Room with River View': 45,
 'Garden Twin Room': 21,
 'Double Hilton Guestroom': 1001,
 'Double Room Disability Access': 129,
 'Superior Double or Twin Room': 10238,
 'Deluxe Double': 1232,
 'Family Room': 1651,
 'Compact Double Room': 685,
 'Superior Premium Queen Room': 33,
 'Superior Room for 1 2 people with Kitchenette': 11,
 'Classic Double Room Loge Classique': 61,
 'Superior Room with 1 Double bed and Sofa 3 adults': 26,
 'City King Room': 551,
 'Superior Queen Room': 3686,
 'Pasha Suite': 13,
 'Deluxe Double Room Annex': 50,
 'Double Room with Extra Bed 2 Adults 1 Child': 20,
 'Twin Guest Room': 1643,
 'Double Room with Two Double Beds': 816,
 'Junior Suite': 3392,
 'Double or Twin Ground Floor': 270,
 'Modern Double Room Narcisse': 4,
 'Superior Room with Queensize Bed and double couch 2 adults 2 children': 193,
 'King Hilton Guest Room': 490,
 'Quadruple Room': 873,
 'Junior Suite Twin 1 2 Adults': 6,
 'Double Room Medium': 54,
 'Executive room with Executive lounge access Free Wifi': 15,
 'Double Room 1 Adult': 483,
 'Double Room with City View': 251,
 'Urban Double or Twin Room': 147,
 'Superior King or Twin Room': 1331,
 'Dorsett Double Room': 787,
 'Suite with Spa Access': 2,
 'Deluxe Double Room with Private Access to Pool and Spa': 63,
 'Privilege Junior Suite with Spa Access': 16,
 'Deluxe Double Room 1 2 Adults': 225,
 'Special Offer Superior Double Room': 102,
 'Classic Twin Room': 1798,
 'Small Double Room': 2373,
 '2 Connecting Rooms 5 people': 16,
 'King Superior Room': 58,
 'Double or Twin Room 1 2 Adults': 1812,
 'Superior Double Double': 72,
 'Twin Deluxe Room': 100,
 'Two Connecting Double or Twin Rooms': 6,
 'Deluxe Room': 2956,
 'Double or Twin Room with Spa Access': 296,
 'Classic Room with Courtyard View': 156,
 'City Suite': 6,
 'Suite with Balcony': 29,
 'Business Double Room': 197,
 'Standard Double Room with Sea View': 23,
 'Suite': 1404,
 'Deluxe Triple Room': 544,
 'King Room': 2135,
 'Superior Double or Twin Room 1 2 Adults': 723,
 '3 rooms': 360,
 'Room with Dock View Main Deck': 17,
 'Superior Shard King': 308,
 'Classic King Twin Room': 109,
 'Duplex': 26,
 'Deluxe Studio': 130,
 'Classic Double Room with Garden View': 71,
 'Superior Triple Room 3 Adults': 40,
 'Family Room 2 Adults 1 Child': 100,
 'Junior Suite with Spa Access': 102,
 'River View Balcony Suite': 14,
 'Superior Twin Room with View': 55,
 'Standard Room with Spa access': 227,
 'Economy Double Room': 880,
 'Standard Room with Queen Bed': 231,
 'Standard Double Twin Room': 1060,
 'Superior': 209,
 'Townhouse Deluxe': 11,
 'Large Room': 171,
 'Deluxe Queen Room': 566,
 'Queen Guest Room with Sofa Bed': 200,
 'Twin Hilton Deluxe': 32,
 'Superior Double or Twin Room with Garden View': 10,
 'Twin Room with Extra Bed 3 Adults': 24,
 'Deluxe Room Barlow Wing': 446,
 'Double Room with Mobile Phone': 16,
 'One Bedroom Apartment': 264,
 'Deluxe Double Studio': 111,
 'One Bedroom Suite': 489,
 'Superior Deluxe Room': 202,
 'Executive Family Room': 231,
 'Grand Deluxe Double or Twin Room': 124,
 'Executive King Room Non Smoking': 72,
 'Standard Double Room with Bridge View': 271,
 'Classic King Room': 977,
 'Queen or Two Double Beds Room': 549,
 'Executive Twin Room': 825,
 'Twin Deluxe Guest Room': 43,
 'Stayed 19 nights': 23,
 'Double Room with View': 478,
 'Master Bedroom Suite': 15,
 'Junior Double Room': 163,
 'Room with Ramblas View': 107,
 'Queen Room Mobility Access': 390,
 'Luxury Double Room with Balcony': 14,
 'Senior Suite 1 3 Adults': 3,
 'Superior Room with Queen size bed and Sofa Bed': 205,
 'Large Triple Room': 40,
 'Studio Triple': 172,
 'Deluxe King Room Wheelchair Accessible': 6,
 'With a pet': 1045,
 'Superior King': 52,
 'Deluxe Double or Twin Room with Mountain View': 40,
 'Studio King Family': 664,
 'Twin Superior Room': 85,
 'Club Room with Club Lounge Access': 13,
 'Classic Double or Twin Room with Spa Access': 202,
 'Standard Guest Room': 84,
 'Standard Room with 2 Single Beds': 223,
 'Comfort Twin Double Room': 231,
 'Junior Double': 78,
 'Comfort Double Room Courtyard Side': 32,
 'Souterraine Double or Twin Room': 110,
 'Classic Double or Twin Room with City View': 121,
 'Economy Double or Twin Room': 50,
 'Standard Double Room with Two Single Beds': 98,
 'Double Deluxe Plus Room': 17,
 'Standard Double': 547,
 'Deluxe Double Room without Window': 28,
 'King Room with Courtyard View': 33,
 'Deluxe Double Room Pigalle 21': 2,
 'Stayed 13 nights': 174,
 'Superior Double or Twin Room with Balcony': 54,
 'Junior King Suite': 45,
 'Double Room with Balcony': 209,
 'Stayed 9 nights': 966,
 'Executive Family Room 2 Adults and 2 Children': 18,
 'Deluxe Room with Two Double Beds': 97,
 'Observatory King': 30,
 'Small Double Room with Extra Bed Annex building': 14,
 'Single Room with Shower': 135,
 'King Guest Room Wheelchair Accessible': 46,
 'Junior King Suite with Lounge Access': 4,
 'Super Deluxe Double Room': 44,
 'Double or Twin Room 2 Adults': 53,
 'Deluxe King Room with River View': 414,
 'Queen Bed Leisure': 91,
 'Large King Room': 48,
 'Executive King Room with Executive Lounge Access': 27,
 'Comfort Double Room': 2005,
 'Standard Compact Double Room': 24,
 'Special Offer Executive Double Twin Room with Access to Nagomi Health': 52,
 'Deluxe Duplex Room': 26,
 'Design Double or Twin Room': 65,
 'Deluxe Double or Twin Room 2 adults 1 child': 90,
 'Two Bedroom Suite with Two Bathrooms': 19,
 'Family Studio': 39,
 'Deluxe Single Room with View': 76,
 'Club King Room with Lounge Access': 16,
 'Superior Room with Spa Fitness Access': 70,
 'Classic Queen Room': 591,
 'Family Room 2 Adults 2 Children': 699,
 'Souterrain Comfort Room': 70,
 'Superior Single Room': 846,
 'Room Selected at Check In': 321,
 'Executive Room with queen size bed and double sofa bed 2 adults 2 children': 30,
 'Queen Double Room': 136,
 'Classic Family Room': 48,
 'Double Room with Sofa Bed': 358,
 'Double or Twin Room with Extra Bed 3 Adults': 42,
 'Two Bedroom Apartment': 133,
 'Double Room Annex': 136,
 'Superior Double Room with View': 76,
 'Basic Single Room': 241,
 'Economy Single Room': 104,
 'Townhouse Club': 9,
 'Club Room': 138,
 'Quality Double or Twin Room': 176,
 'Double Room with Single Bed': 251,
 'Paseo de Gracia Double or Twin Room': 29,
 'Superior Double Room with Sea View': 17,
 'Executive Double or Twin Room': 1061,
 'One Bedroom Queen Suite': 19,
 'Classic Double or Twin Room 1 2 Adults': 99,
 'Superior Double Room with Balcony and City View': 69,
 'Two Connecting Rooms': 110,
 'Queen Room Non Smoking': 526,
 'Hilton Deluxe King Room': 45,
 'Deluxe with Two Double Beds': 280,
 'Royal Mews View King Room': 44,
 'Luxury Quadruple Room': 17,
 'Superior Twin Room Barlow Wing': 109,
 'Superior Room with 2 Single Beds': 288,
 'Junior Suite Avenue': 15,
 'Classic Room with 2 double beds 2 Adults': 35,
 'Superior Room with Double Bed and Sofa Bed': 67,
 'Weekend Offer Standard Studio': 35,
 'Superior Plus Twin Room': 61,
 'King Double Room': 173,
 'Premium Double Room': 449,
 'Superior Double Room with Spa Access': 147,
 'Double Room Courtyard': 6,
 'Standard Quadruple Room': 204,
 'Family Suite 2 Adults 2 Children': 71,
 'Art Twin Room': 49,
 'Double or Twin Room with Bathroom': 35,
 'Special Offer Double Twin Room Stay and Park': 49,
 'Standard Room 1 2 adults': 210,
 'Economy Twin Room': 139,
 'Double or Twin Room with View': 174,
 'Family Room Two connecting Rooms': 15,
 'Privilege Double Room': 175,
 'Superior Double Room with Internal View': 821,
 'Family Room with View': 19,
 'Executive Club Room': 79,
 'Large Penthouse Suite with Terrace and City View': 43,
 'Camper Room': 173,
 'Superior Double Room with City View': 222,
 'Twin Room Disability Access': 112,
 'Family Room with sofa bed': 127,
 'Executive Room': 940,
 'Duplex Double Room': 234,
 'Corner Suite': 76,
 'Superior Triple Room': 546,
 'Spare Room Double': 36,
 'Executive Double Room River View': 214,
 'Deluxe King Room with Club Lounge Access': 39,
 'Club Double or Twin Room': 83,
 'Boudoir Double Room': 35,
 'Maisonette': 82,
 'Comfort Double Room With Sacr Coeur View': 15,
 'Deluxe Double Room with View': 179,
 'Budget Single Room Non Smoking': 20,
 'Junior Suite Blue': 5,
 'City Room': 112,
 'Executive Queen Room with Sofa': 68,
 'Premium Twin Room': 18,
 'Premium Double or Twin Room': 526,
 'Double Suite': 146,
 'King Hilton Plaza Room': 41,
 'Premier King Room with City View': 138,
 'Superior Double or Twin Room with Terrace': 179,
 'Dalston King': 142,
 'Double Room with Terrace': 285,
 '2 Double Rooms next to each other': 3,
 'Studio Double Room': 157,
 'Family Duplex Room': 16,
 'Executive Double Room with Spa Access': 41,
 'Superior Double Room with Park View': 50,
 'Standard Queen Room with Sofa Bed': 107,
 'Deluxe Queen Guestroom': 18,
 'Duplex King Suite 2 Adults 2 Children': 7,
 'King Deluxe Room': 81,
 'Stayed 17 nights': 27,
 'Premium Superior Double Room': 18,
 'Squint Penthouse Suite': 6,
 'Superior Studio Apartment': 41,
 'Penthouse Suite with Terrace and City View': 68,
 'Deluxe Double Room Swimming Pool Hammam Access upon reservation': 3,
 'Andaz Double Room': 75,
 'Cozy Double or Twin Room': 83,
 'Apartment 3 Adults': 23,
 'Superior Queen Suite with Sofa Bed': 101,
 'Queen or Twin Room': 56,
 'Superior Room with a shower or a bath': 24,
 'Superior Double Room with Balcony': 143,
 'King Room with Balcony': 76,
 'Comfort Single Room with Window and Double Bed': 14,
 'Queen Room Disability Access Non Smoking': 30,
 'Double Room 1 2 Adults': 393,
 'Double or Twin Room with Balcony': 152,
 'Executive Single Room': 156,
 'Club Double or Twin Room with Club Lounge Access': 8,
 'Triple Hilton Family Room': 76,
 'Single Room Lower Ground Floor': 40,
 'Superior Double Studio': 14,
 'Two Adjacent Classic Rooms': 20,
 'One Bedroom King Suite with Sofa Bed': 24,
 'Stayed 11 nights': 306,
 'Double Room L': 23,
 'Comfort Double or Twin Room 1 2 Adults': 100,
 'Standard Triple Room with Queen Bed and Sofa Bed': 14,
 'Camper Suite': 28,
 'Garden King Room': 73,
 'Privilege Room with 1 Kingsize Bed': 34,
 'Comfort Room': 544,
 'Accessible Queen Guest Room': 80,
 'Superior Double Room Disability Access': 300,
 'Classic Twin Room with Garden View': 48,
 'Deluxe Designer': 8,
 'Deluxe Junior Suite': 112,
 'Superior Double Room with free unlimited WIFI': 84,
 'Luxury Room 2 Adults with canal view': 14,
 'Standard Room Sopi': 38,
 'Executive Double Room with Whirlpool': 85,
 'Junior Suite with Bath': 4,
 'Deluxe Double Room with Extra Bed': 13,
 'Cosy Single Room': 356,
 'Amsterdam Street Art Queen Guest Room': 10,
 'Tiny Single Room': 36,
 'Queen Room with Sofa Bed': 116,
 'Deluxe Club Double Room': 41,
 'Family Junior Suite 3 Adults 1 Child': 116,
 'Deluxe King Room with Paris View': 10,
 'Superior Room with 1 Double Bed and 1 Sofa Bed 2 places': 10,
 'Executive Double Room with Turkish Bath': 8,
 'Executive Room with Two Double Beds': 26,
 'Triple Room 2 Adults 1 Child': 168,
 'Deluxe King Room with Stadium View': 279,
 'Double Deluxe Room': 290,
 'Superior Quadruple Room With Balcony': 35,
 'Club Single Room': 278,
 'Luxury Suite with whirlpool': 24,
 'Small Single Room': 233,
 'Standard Studio': 68,
 'Premier King Room Barlow Wing': 60,
 'City King or Twin Room': 676,
 'Twin Room with Free Airport Shuttle Service from 5 00am to 00 30am': 54,
 'King Room with City View Top floors': 5,
 'Classic Triple Room': 204,
 'Superior Queen Room with Double Sofa': 54,
 'Classic Room with Queen Bed': 71,
 'Small Single Room with Balcony': 41,
 'Two Bedroom Suite': 69,
 'Executive Deluxe Studio Suite': 42,
 'Triple Family Guestroom': 81,
 'Deluxe Suite': 122,
 'Deluxe Double or Twin Room with Canal View': 226,
 'Double Room with Street View': 193,
 'Superior Double Room with Terrace and Private Pool': 33,
 'Standard Double or Twin Room 1 2 Adults': 55,
 'Loft': 39,
 'Deluxe Double or Twin Room 1 2 Adults': 109,
 'Deluxe Family Room with 1 Double and 2 Single Beds 4 Adults': 22,
 'Club Level Classic Rooms': 6,
 'Superior King Room with River View': 34,
 'Queen Room Upper Floors': 88,
 'Privilege Superior Room': 9,
 'Double Room Disability Access Non Smoking': 31,
 'Executive King Room with View': 13,
 'Double or Twin Room 1 or 2 adults': 49,
 'Classic Triple Room 3 Adults': 64,
 'Twin Room with View': 11,
 'Superior Queen Room with Sofa': 131,
 'Junior Suite 2 Adults': 143,
 'Double Room with Sofa Bed Non Smoking': 224,
 'Standard Room with Two Single Beds Renovated': 4,
 'Superior Double Room Pigalle 17': 7,
 'Executive Club Double Room': 111,
 'Condal Double or Twin Room': 51,
 'Twin Room with Mobile Phone': 6,
 'Junior Suite with Private Access to Pool and Spa': 7,
 'Queen Room with Mobility Access': 259,
 'Panoramic Room': 21,
 'Double or Twin Room with Extra Bed': 173,
 'Queen Room with Sofa Bed Non Smoking': 43,
 'Deluxe King Room with Balcony': 194,
 'Standard Double Room No Window': 348,
 'Double Room with Garden View': 71,
 'Stayed 27 nights': 10,
 'Double Room with Eiffel Tower View': 165,
 'Double Room with City View 1 Adult': 13,
 'Cabin Single Room': 154,
 'Delightful Queen Room': 45,
 'Superior Room with Queen Bed': 108,
 'Club King Room': 109,
 'Superior King Room Eiffel Tower View': 122,
 'Double Room Free Wi Fi': 95,
 'Large Comfort Double or Twin Room': 129,
 'Superior Double or Twin Room with Extra Bed': 25,
 'Double Room with Extra Bed': 150,
 'Business Double or Twin Room': 321,
 'Nhow Premium Double or Twin Room': 11,
 'Deluxe King Room Balcony with Eiffel Tower View': 303,
 'Twin Room with Courtyard View': 25,
 'Standard Queen or Twin Room Lower Ground Floor': 44,
 'Twin Room 1 2 people': 44,
 'Superior Room with canal view': 51,
 'Luxury Family Room': 64,
 'Standard Quad Room': 27,
 'Studio Room': 67,
 'Special Offer Twin Double Room Stay and Park': 16,
 'Single Hilton Guest Room': 30,
 'Premium King Room': 26,
 'Deluxe Queen Room with View': 42,
 'Superior Room Non Smoking': 11,
 'Double Room with French Bed': 61,
 'Luxury King Room': 55,
 'Family Apartment': 25,
 'Double or Twin Room Allergy Free': 37,
 'Double Room Lady Soul': 27,
 'Superior Double Room with Private Patio': 49,
 'Executive Premium Room with a Queen Bed': 44,
 'Privilege Double Room 2 Adults 1 child': 40,
 'Special Offer Double Room': 210,
 'Deluxe King': 19,
 'Special Offer Queen Room': 156,
 'Superior Double or Twin Room with Sauna Access': 9,
 'Loft Suite Disability Access': 6,
 'Premier Twin Room': 96,
 'Superior Double Twin Room': 225,
 'Executive Double Room Eiffel Studio D Artiste with view of Paris': 28,
 'Queen Deluxe Room': 59,
 'Marina Double Suite': 81,
 'Superior Double Room with 1 Double Bed and 1 Sofa Bed 2 places': 103,
 'Double Room Baronne': 39,
 'King Room with Sea View': 1,
 'Executive Double or Twin Room with Harbour View': 31,
 'Wonderful Room': 164,
 'Superior Room with Two Double Beds and Balcony': 51,
 'Comfort Single Room': 87,
 'Deluxe King with Balcony': 170,
 'Standard Room with Spa Access': 49,
 'Romantic Special Offer': 41,
 'Double or Twin Room with Courtyard View': 185,
 'Deluxe Two Bedroom Suite': 3,
 'Superior Studio': 57,
 'Executive Studio': 122,
 'Deluxe Twin Room 3 Adults': 5,
 'Comfort Triple Room': 304,
 'Deluxe Double and Single Room': 200,
 'Standard Room with Queensize bed and Single Sofa Bed': 82,
 'Discovery Double Room': 93,
 'Studio Twin': 34,
 'Superior Queen Room with Pool Access': 30,
 'Classic Double or Twin Room with extra bed': 25,
 'Junior Suite with Terrace': 41,
 'Economy Double Room basement no window': 15,
 'King Junior Suite City View with Access to Executive Lounge': 17,
 'Business Single Room': 68,
 'Deluxe King Room with Water View': 60,
 'Deluxe Twin Room with City View': 41,
 'Luxury Triple Room': 20,
 'King Deluxe One Bedroom Suite with Lounge Access': 2,
 'Double or Twin Room with City View': 192,
 'Standard Twin Room with Sofa': 13,
 'Deluxe Double Room with Spa Bath': 82,
 'Junior Suite with Private Pool': 17,
 'Executive Room with City View': 82,
 'Superior Twin Room with Extra Bed': 45,
 'Privilege Double Room with Saint Germain des Pr s Church View': 5,
 'Deluxe Double or Twin Room with Opera View': 6,
 'Special Offer Twin Room': 13,
 'Attach Suite': 33,
 'Four Seasons King Junior Suite': 4,
 'Superior M Double Room': 78,
 'Two Adjacent Double Rooms': 17,
 'Superior Twin or Double Room': 57,
 'Single Room with Bathroom': 8,
 'Superior Double': 177,

In [ ]:
# модель на признаках с dtypes "object" обучаться не будет, просто выберим их и удалим
#object_columns = [s for s in hotels.columns if hotels[s].dtypes == 'object']
#hotels.drop(object_columns, axis = 1, inplace=True)

In [52]:
# Разбиваем датафрейм на части, необходимые для обучения и тестирования модели  
# Х - данные с информацией об отелях, у - целевая переменная (рейтинги отелей)  
X = hotels.drop(['reviewer_score'], axis = 1)  
y = hotels['reviewer_score']

In [34]:
hotels.describe()

,additional_number_of_scoring,average_score,review_total_negative_word_counts,total_number_of_reviews,review_total_positive_word_counts,total_number_of_reviews_reviewer_has_given,reviewer_score,lat,lng
count,386803.000000,386803.000000,386803.000000,386803.000000,386803.000000,386803.00000,386803.000000,384355.000000,384355.000000
mean,498.246536,8.397231,18.538988,2743.992042,17.776985,7.17725,8.396906,49.443522,2.823402
std,500.258012,0.547881,29.703369,2316.457018,21.726141,11.05442,1.636090,3.466936,4.579043
min,1.000000,5.200000,0.000000,43.000000,0.000000,1.00000,2.500000,41.328376,-0.369758
25%,169.000000,8.100000,2.000000,1161.000000,5.000000,1.00000,7.500000,48.214662,-0.143649
50%,342.000000,8.400000,9.000000,2134.000000,11.000000,3.00000,8.800000,51.499981,-0.000250
75%,660.000000,8.800000,23.000000,3613.000000,22.000000,8.00000,9.600000,51.516288,4.834443
max,2682.000000,9.800000,408.000000,16670.000000,395.000000,355.00000,10.000000,52.400181,16.429233

In [24]:
# Загружаем специальный инструмент для разбивки:  
from sklearn.model_selection import train_test_split

In [28]:
# Наборы данных с меткой "train" будут использоваться для обучения модели, "test" - для тестирования.  
# Для тестирования мы будем использовать 25% от исходного датасета.  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
# Импортируем необходимые библиотеки:  
from sklearn.ensemble import RandomForestRegressor # инструмент для создания и обучения модели  
from sklearn import metrics # инструменты для оценки точности модели  
  
# Создаём модель  
regr = RandomForestRegressor(n_estimators=100)  
      
# Обучаем модель на тестовом наборе данных  
regr.fit(X_train, y_train)  
      
# Используем обученную модель для предсказания рейтинга отелей в тестовой выборке.  
# Предсказанные значения записываем в переменную y_pred  
y_pred = regr.predict(X_test)

In [ ]:
# Сравниваем предсказанные значения (y_pred) с реальными (y_test), и смотрим насколько они отличаются  
# Метрика называется Mean Absolute Percentage Error (MAPE) и показывает среднюю абсолютную процентную ошибку предсказанных значений от фактических.  
print('MAPE:', metrics.mean_absolute_percentage_error(y_test, y_pred))

Небольшой бонус:

In [16]:
#убираем признаки которые еще не успели обработать, 
# модель на признаках с dtypes "object" обучаться не будет, просто выберим их и удалим
#object_columns = [s for s in hotels.columns if hotels[s].dtypes == 'object']
#hotels.drop(object_columns, axis = 1, inplace=True)

# заполняем пропуски самым простым способом
#hotels = hotels.fillna(0)

In [13]:
# непрерывные признаки
num_cols = ['total_number_of_reviews', 'review_total_negative_word_counts', 'additional_number_of_scoring', 
           'review_total_positive_word_counts', 'total_number_of_reviews_reviewer_has_given', 
           'reviewer_score']

# категориальные признаки
cat_cols = ['average_score', 'lat', 'Ing']

In [21]:
# непрерывные признаки
num_cols = ['total_number_of_reviews', 'review_total_negative_word_counts', ...]

# категориальные признаки
cat_cols = ['average_score', 'lat', ...]

In [22]:
y=y.astype('int')

...
from sklearn.feature_selection import chi2 # хи-квадрат

imp_cat = pd.Series(chi2(X[cat_cols], y)[0], index=cat_cols)
imp_cat.sort_values(inplace = True)
imp_cat.plot(kind = 'barh')

KeyError: '[Ellipsis] not in index'